/*
 * This source file was generated by the Gradle 'init' task
 */
package juegoparchis;

public class MainJuego {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new MainJuego().getGreeting());
    }
}
