/*
 * This source file was generated by the Gradle 'init' task
 */
package juegoparchis;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        MainJuego classUnderTest = new MainJuego();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
